###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "nombre": "ramon",
    "apellido": "mongol",
    "edad": 55
}

###
DELETE http://localhost:9000/api/2 HTTP/1.1

###
PUT http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "ramon",
    "apellido": "lista",
    "edad": 44
}
